const mongoose  = require('mongoose');

//schema
//id is autogenerated
const postSchema = mongoose.Schema(
    {
        title: String,
        content: String,
        user_id: String
    }
)
module.exports = mongoose.model('Post', postSchema);